name: Test
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Enable experimental features for the Docker CLI
        run: |
          mkdir -p ~/.docker
          echo $'{\n  "experimental": "enabled"\n}' | sudo tee ~/.docker/config.json
          sudo service docker restart
          docker version -f '{{.Client.Experimental}}'
          docker buildx version
      - name: Setup a Docker builder
        run: |
          docker buildx create --name ci --use
          docker buildx inspect --bootstrap
      - name: Set up containerd
        uses: crazy-max/ghaction-setup-containerd@v1
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.2'
      - uses: actions/checkout@v2
      - name: Export the OCI image
        run: docker buildx build --tag hello -o type=oci,dest=- . > hello.tar
      - name: Build the Go binary
        run: go build -o main ./main.go
      - name: Import the OCI image in containerd
        run: |
          sudo ctr -n=example images import hello.tar
      - name: Run the Go binary
        run: |
          sudo ./main
